config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from oscar.app import application
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
#    path("", include((application.urls, 'oscar'),)),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", TemplateView.as_view(template_name="squeeze/pages/home.html"), name="home"),
    path(
        "shopping/",
        TemplateView.as_view(template_name="squeeze/pages/shopping.html"),
        name="shopping",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management

    path("users/", include("ink.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    #
    # Your stuff: custom urls includes go here
    #
    path("squeeze/", include("squeeze.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ink/users/urls.py
from django.urls import path

from ink.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

squeeze/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from oscar.app import application
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = []

ink/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from localflavor.us.models import USZipCodeField, USStateField
from colorful.fields import RGBColorField
from django.db.models import *


class User(AbstractUser):

    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

squeeze/models.py
from django.db import models

# Create your models here.

ink/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

ink/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

squeeze/views.py
from django.shortcuts import render

# Create your views here.

ink/templates/pages/about.html
{% extends "base.html" %}

ink/templates/pages/shopping.html
{% extends "base.html" %}
{% load staticfiles %}

<title>{% block title %}Shopping Cart{% endblock title %}</title>

{% block content %}
hey
{% endblock content %}

squeeze/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

squeeze/templates/squeeze/account/account_inactive.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock %}

{% block inner %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This account is inactive." %}</p>
{% endblock %}

squeeze/templates/squeeze/account/base.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<style>

h1{
    font-family: "Whoa!", sans-serif;
    color: #000234;
}
p{
  font-family: "Permanent Marker", sans-serif;
    color: #000234;
}
</style>

<div class="row">
  <div class="col-md-6 offset-md-3">
    {% block inner %}{% endblock %}
  </div>
</div>
{% endblock %}

squeeze/templates/squeeze/account/email.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Account" %}{% endblock %}

{% block inner %}
<h1>{% trans "E-mail Addresses" %}</h1>

{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="radio">
  <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

    <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

    {{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
    {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
  </label>
</div>
  {% endfor %}

<div class="form-group">
      <button class="secondaryAction btn btn-primary" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction btn btn-primary" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction btn btn-primary" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}


    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>

{% endblock %}


{% block javascript %}
{{ block.super }}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();

$('.form-group').removeClass('row');
</script>
{% endblock %}

squeeze/templates/squeeze/account/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block inner %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button class="btn btn-primary" type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

squeeze/templates/squeeze/account/login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block inner %}
<h1>{% trans "Sign In" %}</h1>
{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form|crispy }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction btn btn-primary" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

squeeze/templates/squeeze/account/logout.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block inner %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button class="btn btn-danger" type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

squeeze/templates/squeeze/account/password_reset.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block inner %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

squeeze/templates/squeeze/account/password_reset_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block inner %}
    <h1>{% trans "Password Reset" %}</h1>
    
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}
    
    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% endblock %}

squeeze/templates/squeeze/account/password_reset_from_key.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block inner %}
    <h1>{% if token_fail %}{% trans "Bad Token" %}{% else %}{% trans "Change Password" %}{% endif %}</h1>

    {% if token_fail %}
        {% url 'account_reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action=".">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

squeeze/templates/squeeze/account/password_reset_from_key_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block inner %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

squeeze/templates/squeeze/account/password_set.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Set Password" %}{% endblock %}

{% block inner %}
    <h1>{% trans "Set Password" %}</h1>

    <form method="POST" action="{% url 'account_set_password' %}" class="password_set">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="action" value="{% trans 'Set Password' %}"/>
    </form>
{% endblock %}

squeeze/templates/squeeze/account/signup.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block inner %}
<h1>{% trans "Sign Up" %}</h1>

<p>{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p>

<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
  {% csrf_token %}
  {{ form|crispy }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <button class="btn btn-primary" type="submit">{% trans "Sign Up" %} &raquo;</button>
</form>

{% endblock %}

squeeze/templates/squeeze/account/signup_closed.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block inner %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}

squeeze/templates/squeeze/account/verified_email_required.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block inner %}
<h1>{% trans "Verify Your E-mail Address" %}</h1>

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This part of the site requires us to verify that
you are who you claim to be. For this purpose, we require that you
verify ownership of your e-mail address. {% endblocktrans %}</p>

<p>{% blocktrans %}We have sent an e-mail to you for
verification. Please click on the link inside this e-mail. Please
contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

<p>{% blocktrans %}<strong>Note:</strong> you can still <a href="{{ email_url }}">change your e-mail address</a>.{% endblocktrans %}</p>


{% endblock %}

squeeze/templates/squeeze/base.1.html
{%extends 'oscar/base.html' %}

{% load static i18n %}
<!DOCTYPE html>
{% load socialaccount %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa|Coming+Soon|Permanent+Marker">
  <iframe id="audio" src="{% static 'media/spray_sound.mp3' %}" allow="autoplay" style="display:none"></iframe>
  <source src="{% static 'media/spray_audio.mp3' %}" type="audio/mpeg">
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



  {% block css %}
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  <link href="{% static 'css/ink_bootstrap.css' %}" rel="stylesheet">
  {% endblock css %}
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
</head>

<body>
  <div id="fb-root"></div>

  <script async defer crossorigin="anonymous"
    src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=275166813408739&autoLogAppEvents=1">
  </script>
  <style>
    .navbar {
      background-image: url("{% static '' %}");
      background-repeat: no-repeat;
      background-size: cover;
      align-content: center;
    }

  </style>
  <div class="mb-1">
    <nav class="navbar navbar-expand-lg navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler">
          <img style="height:50px" src="{% static 'images/fingerprint_flat.svg' %}" alt=""></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
        <img style="width: 200px;" src="{% static 'images/inkpressure_logo.svg' %}" alt="logo"></a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
          {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
          <p><a href="{% provider_login_url 'google' %}">Log In with Gmail</a></p>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopping' %}">Shopping Cart</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
  {% if user.is_authenticated %}
  <h6 style="float: right; color: #00c300;">Welcome Back {{ user.username }} !!!</h6>
  {% endif %}
  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
    {% endif %}


    {% block content %}

    {% endblock content %}
    <style>
      .footer {
        left: 0;
        bottom: 0;
        width: 100%;

      }

    </style>
    <footer class="footer">
      <div class="container-fluid">
        <p style="color: white;">Contact us on Social Media!</p>
        <span class="text-muted">
          <a href="https://www.facebook.com/Inkpressurecom-1982157881897017/?modal=admin_todo_tour">
            <img style="width: 35px; margin: 14px" src="{% static 'images/socials/facebook_icon.png' %}"
              alt="fb logo"></a>
          <a href="https://www.instagram.com/inkpressure/">
            <img style="width: 35px; margin: 14px" src="{% static 'images/socials/instagram_icon.png' %}"
              alt="insta logo"></a>
          <a href="https://twitter.com/Inkpressure2">
            <img style="width: 35px; margin: 14px" src="{% static 'images/socials/twitter_icon.png' %}"
              alt="twitter logo"></a>
          <a href="https://www.youtube.com/channel/UCBN3SCNve1eBN47lU88Cd1Q?disable_polymer=true"><img
              style="width: 35px; margin: 18px" src="{% static 'images/socials/youtube_icon.png' %}"
              alt="youtube logo"></a>
        </span>
      </div>
      <div class="fb-like" data-href="https://www.inkpressure.com" data-width="60" data-layout="standard"
        data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>

    </footer>

    {% block modal %}


    {% endblock modal %}

    {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="https://cdn.jsdelivr.net/npm/iro-dynamic-css/dist/iro-dynamic-css.min.js"></script>

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
</body>

</html>

squeeze/templates/squeeze/base.html
{%extends 'oscar/base.html' %}
{%load staticfiles %}
{% load static i18n %}

<head>
<title>{% block title %}{% endblock title %}</title>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="author" content="">


{% block favicon %}
<link rel="shortcut icon" href="{% static "images/favicons/favicon.ico" %}" />
{% endblock %}

{# Block where global CSS will go. #}
{% block styles %}
<link href={% static "css/squeeze.css" %} rel="stylesheet" />
  <link href={% static "css/ink_bootstrap.css" %} rel="stylesheet" />

{% endblock %}

{# Additional CSS - specific to certain pages #}
{% block extrastyles %}{% endblock %}

{% block extrahead %}{% endblock %}

{% block tracking %}
{# Default to using Google analytics #}
{% include "partials/google_analytics.html" %}
{% endblock %}
</head>

{% block body_id %}default{% endblock %}" class="{% block body_class %}default{% endblock %}">



{% block layout %}

{% endblock %}
{# Main content goes in this 'layout' block #}


{% block scripts %}
<script type="text/javascript" src={% static 'js/squeeze.js' %}></script>
{% endblock %}


{% block extrascripts %}{% endblock %}

{% block onbodyload %}{% endblock %}

squeeze/templates/squeeze/pages/shopping.html
{% extends "squeeze/base.html" %}
{% load staticfiles %}

<title>{% block title %}Shopping Cart{% endblock title %}</title>

{% block content %}
hey
{% endblock content %}

squeeze/templates/squeeze/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

squeeze/templates/squeeze/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

squeeze/templates/squeeze/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}